"""aliados em missoes

Revision ID: 398ab75549be
Revises: f37c005df81a
Create Date: 2026-09-12 22:06:04.484261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398ab75549be'
down_revision: Union[str, None] = 'f37c005df81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missao_aliados',
    sa.Column('missao_id', sa.String(), nullable=False),
    sa.Column('aliado_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['aliado_id'], ['aliados.id'], ),
    sa.ForeignKeyConstraint(['missao_id'], ['missoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('missao_id', 'aliado_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missao_aliados')
    # ### end Alembic commands ###
