"""schema v3 escopo reduzido

Revision ID: 73f6bca2f3f5
Revises: 
Create Date: 2026-09-12 21:43:13.385731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f6bca2f3f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ciclo', sa.Integer(), nullable=False),
    sa.Column('madeira', sa.Integer(), nullable=False),
    sa.Column('pedra', sa.Integer(), nullable=False),
    sa.Column('metais', sa.Integer(), nullable=False),
    sa.Column('suprimentos', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_estado_single'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locais',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.CheckConstraint("status IN ('Livre','Neutro','Hostil')", name='ck_local_status'),
    sa.CheckConstraint('x >= 0 AND x <= 100', name='ck_local_x'),
    sa.CheckConstraint('y >= 0 AND y <= 100', name='ck_local_y'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tropas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantidade >= 0', name='ck_tropa_qtd'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('local_id', sa.String(), nullable=True),
    sa.Column('dt', sa.Integer(), nullable=False),
    sa.Column('notas', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("tipo IN ('B','R','C')", name='ck_missao_tipo'),
    sa.ForeignKeyConstraint(['local_id'], ['locais.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missao_tropas',
    sa.Column('missao_id', sa.String(), nullable=False),
    sa.Column('tropa_id', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantidade > 0', name='ck_mt_qtd'),
    sa.ForeignKeyConstraint(['missao_id'], ['missoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tropa_id'], ['tropas.id'], ),
    sa.PrimaryKeyConstraint('missao_id', 'tropa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missao_tropas')
    op.drop_table('missoes')
    op.drop_table('tropas')
    op.drop_table('locais')
    op.drop_table('estado')
    # ### end Alembic commands ###
