"""aliados informativos

Revision ID: f37c005df81a
Revises: 73f6bca2f3f5
Create Date: 2026-09-12 22:01:58.748433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37c005df81a'
down_revision: Union[str, None] = '73f6bca2f3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliados',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('bonus', sa.String(), nullable=False),
    sa.Column('habilidade', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aliados')
    # ### end Alembic commands ###
